-- V5__fix_naturezas_e_seed_completo.sql
-- 1. Corrige caracteristica de todas as naturezas para 'Criminal'
-- 2. Insere naturezas faltantes
-- 3. Popula ocorrencias da Se (delegacia_id=1) e Bom Retiro (delegacia_id=2)

-- ── 1. CORRIGIR CARACTERISTICA ─────────────────────────────
UPDATE natureza SET caracteristica = 'Criminal';

-- ── 2. INSERIR NATUREZAS FALTANTES ─────────────────────────
INSERT IGNORE INTO natureza (natureza, caracteristica) VALUES
('LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO', 'Criminal'),
('LESÃO CORPORAL CULPOSA - OUTRAS',                 'Criminal'),
('FURTO DE VEÍCULO',                                'Criminal'),
('ROUBO DE VEÍCULO',                                'Criminal'),
('ROUBO A BANCO',                                   'Criminal'),
('ROUBO DE CARGA',                                  'Criminal');

-- ── 3. LIMPAR OCORRENCIAS EXISTENTES ───────────────────────
DELETE FROM ocorrencia;
ALTER TABLE ocorrencia AUTO_INCREMENT = 1;

-- ── 4. SÉ (delegacia_id=1) ─────────────────────────────────

-- HOMICÍDIO DOLOSO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,0,'2024-01-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,1,'2024-02-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-03-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-04-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-05-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-06-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-07-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-08-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,1,'2024-09-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-10-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-11-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-12-01' FROM natureza WHERE natureza='HOMICÍDIO DOLOSO';

-- Nº VÍTIMAS HOMICÍDIO DOLOSO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,0,'2024-01-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,1,'2024-02-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-03-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-04-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-05-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-06-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-07-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-08-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,1,'2024-09-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-10-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-11-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO' UNION ALL
SELECT id,1,0,'2024-12-01' FROM natureza WHERE natureza='Nº DE VÍTIMAS EM HOMICÍDIO DOLOSO';

-- HOMICÍDIO CULPOSO TRÂNSITO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,0,'2024-01-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-02-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-03-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-04-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,2,'2024-05-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-06-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-07-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-08-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,1,'2024-09-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,1,'2024-10-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-11-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,0,'2024-12-01' FROM natureza WHERE natureza='HOMICÍDIO CULPOSO POR ACIDENTE DE TRÂNSITO';

-- TENTATIVA DE HOMICÍDIO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,0,'2024-01-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,2,'2024-02-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-03-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,1,'2024-04-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-05-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-06-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,1,'2024-07-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,1,'2024-08-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-09-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-10-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-11-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO' UNION ALL
SELECT id,1,0,'2024-12-01' FROM natureza WHERE natureza='TENTATIVA DE HOMICÍDIO';

-- LESÃO CORPORAL DOLOSA
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,9, '2024-01-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,9, '2024-02-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,7, '2024-03-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,14,'2024-04-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,13,'2024-05-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,14,'2024-06-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,15,'2024-07-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,11,'2024-08-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,9, '2024-09-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,11,'2024-10-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,14,'2024-11-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA' UNION ALL
SELECT id,1,10,'2024-12-01' FROM natureza WHERE natureza='LESÃO CORPORAL DOLOSA';

-- LESÃO CORPORAL CULPOSA TRÂNSITO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,2, '2024-01-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,4, '2024-02-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,5, '2024-03-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,5, '2024-04-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,5, '2024-05-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,7, '2024-06-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,1, '2024-07-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,3, '2024-08-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,7, '2024-09-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,6, '2024-10-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,6, '2024-11-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO' UNION ALL
SELECT id,1,11,'2024-12-01' FROM natureza WHERE natureza='LESÃO CORPORAL CULPOSA POR ACIDENTE DE TRÂNSITO';

-- ROUBO OUTROS
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,52,'2024-01-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,46,'2024-02-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,48,'2024-03-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,31,'2024-04-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,45,'2024-05-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,42,'2024-06-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,44,'2024-07-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,31,'2024-08-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,26,'2024-09-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,37,'2024-10-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,31,'2024-11-01' FROM natureza WHERE natureza='ROUBO - OUTROS' UNION ALL
SELECT id,1,22,'2024-12-01' FROM natureza WHERE natureza='ROUBO - OUTROS';

-- FURTO OUTROS
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,372,'2024-01-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,287,'2024-02-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,303,'2024-03-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,314,'2024-04-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,311,'2024-05-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,357,'2024-06-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,349,'2024-07-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,274,'2024-08-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,227,'2024-09-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,266,'2024-10-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,241,'2024-11-01' FROM natureza WHERE natureza='FURTO - OUTROS' UNION ALL
SELECT id,1,189,'2024-12-01' FROM natureza WHERE natureza='FURTO - OUTROS';

-- FURTO DE VEÍCULO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,7, '2024-01-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,7, '2024-02-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,9, '2024-03-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,4, '2024-04-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,6, '2024-05-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,5, '2024-06-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,10,'2024-07-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,6, '2024-08-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,4, '2024-09-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,7, '2024-10-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,10,'2024-11-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO' UNION ALL
SELECT id,1,8, '2024-12-01' FROM natureza WHERE natureza='FURTO DE VEÍCULO';

-- ESTUPRO
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT id,1,0,'2024-01-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-02-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-03-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-04-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-05-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,1,'2024-06-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-07-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,1,'2024-08-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,1,'2024-09-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-10-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-11-01' FROM natureza WHERE natureza='ESTUPRO' UNION ALL
SELECT id,1,0,'2024-12-01' FROM natureza WHERE natureza='ESTUPRO';

-- ── 5. BOM RETIRO (delegacia_id=2) — copia da Se ──────────
-- ATENÇÃO: substitua por dados reais do Bom Retiro quando tiver
INSERT INTO ocorrencia (natureza_id, delegacia_id, quantidade, data)
SELECT natureza_id, 2, quantidade, data FROM ocorrencia WHERE delegacia_id = 1;